### ISSUE TITLE
Faulting module name: Qt5Core.dll, version: 5.15.0.0, time stamp: 0x5eb90ecb

### ISSUE THREAD

**Issue by Tashaa78** [hkpanchani/Bulk-Whatsapp-Sender#7]
**Describe the bug**
After installation, trying to execute any command on the interface causes the application to crash. Even trying to create an account the application crashes.

**To Reproduce**
1. Go to file
2. Click on 'Add Account'
3. Enter Account Name
4. Application crashes in a moment.
5. Goto Event Viewer and select Windows Log and then Application.
6. Select the most recent error and check if it was thrown by Bulk WhatsApp Sender.exe

**Expected behavior**
Application should open the browser and add an account

**Screenshots**
![image](https://user-images.githubusercontent.com/18499856/144483146-7a0ec562-c109-4753-90cb-ea855d8bcde6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Insiders Preview build 22509.1000
 - Chrome Version: 96.0.4664.45
 - 
**Additional context**

**Comment by Tashaa78** [comment]
Figured out this issue is because of an outdated chromium driver: Upgrading the driver fixes the issue. 
![image](https://user-images.githubusercontent.com/18499856/145014296-c0589ac1-adf6-4d9d-a122-2d5d80012e44.png)
I don't know if this is a thing I can do a PR for since everyone will have almost different versions of chrome. Maybe stating the version of chrome supported by the current driver will be a great option.

**Comment by amanmakwana** [comment]
For now we can stick to latest version of chrome driver. still than if you can help me figure out dynamic chrome drivers at the time of execution if it can check version of chrome and download the driver at run time would be great
